# Generated by Django 2.1.2 on 2018-10-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='writter',
        ),
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
